services:
  db:
    container_name: postgres-development
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    expose:
      - 5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=team_task_board

  db-testing:
    container_name: postgres-testing
    image: postgres:16-alpine
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=team_task_board_test

